### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by langston-barrett** [TentativeConvert/LaTeX-Note-Importer-for-Anki#1]
First of all, thank you for making such a wonderful bit of code, it was just the thing I needed. I doubly appreciate that you've made the source available!

However, I can't seem to find the license for this code. From http://choosealicense.com/no-license [1]:

> You’ll have to check with your own legal counsel regarding your particular project, but generally speaking, the absence of a license means that default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work.

Did you intend for this code to be open source? If so, can you upload a license, or point me to it?

Thanks!

[1]: See also: the Berne Convention, the international law: http://zvon.org/law/r/bern.html#intro

**Comment by TentativeConvert** [comment]
I simply forgot about adding a license.  Thanks for the reminder!
