### ISSUE TITLE
I've made a project that you might find useful

### ISSUE THREAD

**Issue by langston-barrett** [TentativeConvert/LaTeX-Note-Importer-for-Anki#3]
This automatically creates notes in your supported import format. If you take math notes, this may be helpful! If not, sorry for the spam :) thought it might be nice to know that I'm still using and appreciating this!

https://github.com/siddharthist/amsthm-to-anki

**Comment by TentativeConvert** [comment]
Thanks a lot for creating this project and making me aware of it!  I’ve place a pointer to your program on [Anki's info page for the Note Importer](https://ankiweb.net/shared/info/1199027445?ok=2).

Personally, I've found that writing useful mathematical flash cards is quite a challenge.  They tend to get way too long and difficult.  But when one already has a lecture script,  putting it through your program will probably produce a useful starting point.
