### ISSUE TITLE
Handling of multi-file documents.

### ISSUE THREAD

**Issue by DurhamSmith** [TentativeConvert/LaTeX-Note-Importer-for-Anki#8]
First off thanks for the great tool. 

I often write multiple .tex files and `\include{} `or `\input{}` them. These files do not contain `\begin{document}` and `\end{document}`. This leads to a problem in importing them into anki, and the following error is reported:

> 
> Import failed. Debugging info:
> Traceback (most recent call last):
>   File "/usr/share/anki/aqt/importing.py", line 308, in importFile
>     importer.open()
>   File "/home/dd/.local/share/Anki2/addons21/1199027445/lateximport.py", line 58, in open
>     self.cacheFile()
>   File "/home/dd/.local/share/Anki2/addons21/1199027445/lateximport.py", line 64, in cacheFile
>     self.openFile()
>   File "/home/dd/.local/share/Anki2/addons21/1199027445/lateximport.py", line 70, in openFile
>     self.processFile(str(self.fileobj.read(), "utf-8"))
>   File "/home/dd/.local/share/Anki2/addons21/1199027445/lateximport.py", line 212, in processFile
>     self.preamble, document, ci = pieces[0]
> IndexError: list index out of range

With included `\begin{document}` and `\end{document}` the file is imported correctly. Would it be possible to remove the requirement for these tags for correct import?

**Comment by TentativeConvert** [comment]
As a quick fix, would you consider using the [standalone package](https://ctan.org/pkg/standalone?lang=en) in your setup?  If haven't tested this, but my understanding is that if you include `\usepackage{standalone}` in your main file, then you can use

    \documentclass{standalone}
    \begin{document}
    ... 
    \end{document} 

in the files that you want to `include`.  

It probably wouldn't be too difficult to fix the behaviour of the addon, but now that people have been using it for years I'm a bit afraid of breaking other peoples' workflows by changing it.

**Comment by TentativeConvert** [comment]
I wrote a [fix](https://github.com/TentativeConvert/LaTeX-Note-Importer-for-Anki/commit/05584daf839344406b00a0d50c82bf421795e45f) for this problem for Anki 2.1.  Could you test this and see whether it works for you before I deploy it via Ankis website?  You just need to copy the current version of [`lateximport.py`](https://github.com/TentativeConvert/LaTeX-Note-Importer-for-Anki/blob/master/Anki%202.1/latexbiport/lateximport.py) to your installation of the add-on.  To find that installation, open Anki, go to `Tools` > `Add-ons`, select `LatTeX Note Importer` and click on `View Files`.

**Comment by DurhamSmith** [comment]
Marcus, 

Thanks for the suggestion and fix. Both worked for me. I (quickly) tried some expected failure mode for the fix and it held up well. I will notify if I run into any issues with it. Appreciate the fast work and wonderful plugin.

D
